###########
### Coc ###
###########

[[plugins]]
repo     = 'neoclide/coc.nvim'
build    = 'yarn install --frozen-lockfile'
hook_add = 'call init#coc#hook_add()'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo     = 'liuchengxu/vista.vim'
depends  = ['coc.nvim', 'lightline.vim']
hook_add = 'call init#vista#hook_add()'

###################
### Dark Powers ###
###################

[[plugins]]
repo  = 'Shougo/dein.vim'

[[plugins]]
repo  = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo      = 'Shougo/neomru.vim'

######################
### マルチカーソル ###
######################

[[plugins]]
repo = 'terryma/vim-multiple-cursors'
hook_add = 'call init#vim_multiple_cursors#hook_add()'

[[plugins]]
repo     = 'osyo-manga/vim-over'
hook_add = 'nnoremap <silent> <Leader>o :OverCommandLine<CR>'

[[plugins]]
repo     = 'terryma/vim-expand-region'
hook_add = '''
vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)
'''

####################
### 文法チェック ###
####################

[[plugins]]
repo     = 'w0rp/ale'
hook_add = 'call init#ale#hook_add()'

########################
### Syntax Highlight ###
########################
[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = ['python']
'''

# [[plugins]]
# repo = 'jelera/vim-javascript-syntax'
# repo = 'othree/yajs.vim'

###########
### Git ###
###########

[[plugins]]
repo = 'tpope/vim-fugitive'

# [[plugins]]
# repo = 'cohama/agit.vim'

# [[plugins]]
# repo = 'airblade/vim-gitgutter'

#############
### Filer ###
#############

[[plugins]]
repo     = 'scrooloose/nerdtree.git'
hook_add = 'call init#nerdtree#hook_add()'

# [[plugins]]
# repo = 'kristijanhusak/defx-icons'
# hook_add = 'call init#defx_icons#hook_add()'
#
# [[plugins]]
# repo = 'Shougo/defx.nvim'
# hook_add = 'call init#defx#hook_add()'
# [[plugins]]

####################
### カラーテーマ ###
####################

# [[plugins]]
# repo = 'dracula/vim'

[[plugins]]
repo = 'kaicataldo/material.vim'
hook_add = '''
let g:material_terminal_italics = 0
let g:material_theme_style = 'palenight'
'''

[[plugins]]
repo = 'rhysd/vim-color-spring-night'
hook_add = '''
let g:spring_night_kill_italic = 1
let g:spring_night_high_contrast = 1
'''

##################
### Statusline ###
##################
[[plugins]]
repo     = 'itchyny/lightline.vim'
hook_add = 'call init#lightline#hook_add()'

#############
### Mics ####
#############

[[plugins]]
repo = 'deris/vim-shot-f'

[[plugins]]
repo = 'machakann/vim-highlightedyank'


[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
let g:winresizer_vert_resize = 1
let g:winresizer_horiz_resize = 1
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo     = 'Yggdroot/indentLine'
hook_add = 'call init#indentLine#hook_add()'

# [[plugins]]
# repo     = 'ryanoasis/vim-devicons'
# hook_add = 'call init#vim_devicons#hook_add()'

[[plugins]]
repo     = 'dbakker/vim-projectroot'
hook_add = 'call init#vim_projectroot#hook_add()'

# http://vimcasts.org/episodes/aligning-text-with-tabular-vim/
# [[plugins]]
# repo = 'godlygeek/tabular'

# [[plugins]]
# repo     = 'luochen1990/rainbow'
# hook_add = 'call init#rainbow#hook_add()'

[[plugins]]
repo     = 'andymass/vim-matchup'
hook_add = 'let g:loaded_matchit = 1'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo     = 'junegunn/vim-easy-align'
hook_add = '''
nmap ga <Plug>(EasyAlign)
xmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'voldikss/vim-floaterm'
hook_add ='''
let g:floaterm_winblend = 10
let g:floaterm_width = 100
let g:floaterm_position = 'center'
nmap <silent> <leader>1           :FloatermToggle<CR>i
'''
