[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_exclude_filetypes = ['help', 'nerdtree']
let g:indent_guides_auto_colors = 0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=237 ctermbg=237
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=238 ctermbg=238
" let g:indent_guides_guide_size = 1
'''

[[plugins]] # j,kによる移動を爆速に
repo = 'rhysd/accelerated-jk'
hook_add = '''
let g:accelerated_jk_enable_deceleration = 1
nmap j <Plug>(accelerated_jk_gj)
nmap k <Plug>(accelerated_jk_gk)
'''

################
### terminal ###
################
# tmuxやscreen経由で別ペインに転送する
[[plugins]]
repo = 'jpalardy/vim-slime'


###################
### CTAGS/GTAGS ###
###################

[[plugins]]
repo = 'jsfaint/gen_tags.vim'
hook_add = '''
let g:gen_tags#ctags_auto_gen = 1
let g:gen_tags#gtags_auto_gen = 1
'''

[[plugins]]
repo = '5t111111/alt-gtags.vim'
hook_add = '''
map <C-n> :cn<CR>
map <C-p> :cp<CR>
nnoremap <Leader>g :AltGtags<CR>
nnoremap <Leader>h :AltGtags -r<CR>
nnoremap <Leader>k :AltGtags -s<CR>
'''

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = 'nmap <F8> :TagbarToggle<CR>'

##################
### Statusline ###
##################
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
set laststatus=2
let g:airline_powerline_fonts = 1
let g:airline_section_b = "%t %M"
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_idx_mode = 1
let g:airline#extensions#whitespace#mixed_indent_algo = 1
let g:airline_theme = 'tomorrow'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

